# Generated by Django 4.1.3 on 2022-12-03 04:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import siskerma.app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CooperationDocumentChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cooperationchoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CooperationFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(max_length=255, upload_to=siskerma.app.models.path_and_rename)),
                ('document', models.FileField(max_length=255, upload_to=siskerma.app.models.path_and_rename)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=125)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_createdby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.fakultas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CooperationDucument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=125)),
                ('type', models.IntegerField(choices=[(1, 'IA'), (2, 'MOA'), (3, 'MOU')])),
                ('period', models.IntegerField(choices=[(1, 'Berdasar Tanggal'), (2, 'Tidak Dibatasi')])),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('responsible_name', models.CharField(max_length=125)),
                ('responsible_position', models.CharField(max_length=255)),
                ('responsible_approval_name', models.CharField(max_length=125)),
                ('responsible_approval_position', models.CharField(max_length=255)),
                ('responsible_email', models.EmailField(max_length=254)),
                ('status', models.IntegerField()),
                ('expied_date', models.DateTimeField()),
                ('choices_set', models.ManyToManyField(related_name='cooperationdocument_set', through='app.CooperationDocumentChoice', to='app.cooperationchoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cooperationdocumentchoice',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cooperationducument'),
        ),
        migrations.AddField(
            model_name='worker',
            name='prodi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.prodi'),
        ),
    ]
