# Generated by Django 4.1.3 on 2023-01-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cooperationducument_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperationducument',
            name='fakultas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fakultas'),
        ),
        migrations.AlterField(
            model_name='cooperationducument',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft Pengajuan'), (2, 'Belum Divalidasi'), (3, 'Sudah Divalidasi'), (4, 'Draft Kadaluarsa'), (5, 'Disetujui Oleh Universitas'), (6, 'Ditolak')]),
        ),
    ]
