# Generated by Django 4.1.3 on 2023-01-11 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fakultas_last_ai_number_fakultas_last_moa_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=125)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cooperationducument',
            name='step',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cooperationducument',
            name='number',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='cooperationducument',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft Pengajuan'), (2, 'Disetujui Oleh Kaprodi'), (3, 'Disetujui OLeh Dekan'), (4, 'Draft Kadaluarsa'), (5, 'Disetujui Oleh Rektor'), (6, 'Ditolak')]),
        ),
        migrations.CreateModel(
            name='HistoryDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=125)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=125, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Disetujui'), (2, 'Ditolak')])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.history')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='history',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cooperationducument'),
        ),
        migrations.AddField(
            model_name='history',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
