# Generated by Django 4.1.3 on 2023-01-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_history_cooperationducument_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cooperationducument',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft Pengajuan'), (2, 'Disetujui Oleh Kaprodi'), (3, 'Disetujui OLeh Dekan'), (4, 'Disetujui Oleh Rektor'), (5, 'Draft Kadaluarsa'), (6, 'Ditolak')]),
        ),
        migrations.AlterField(
            model_name='history',
            name='label',
            field=models.CharField(default='Pengajuan', max_length=125),
        ),
    ]
