# Generated by Django 4.1.3 on 2023-01-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_history_number_alter_cooperationducument_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='historydetail',
            options={'ordering': ['created_at']},
        ),
    ]
