# Generated by Django 4.1.3 on 2023-01-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cooperationdocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakultas',
            name='last_ai_number',
        ),
        migrations.RemoveField(
            model_name='fakultas',
            name='last_moa_number',
        ),
        migrations.RemoveField(
            model_name='fakultas',
            name='last_mou_number',
        ),
        migrations.AlterField(
            model_name='cooperationdocument',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft Pengajuan'), (1, 'Belum Divalidasi'), (2, 'Disetujui Oleh Prodi'), (3, 'Disetujui Oleh Fakultas'), (4, 'Draft Kadaluarsa'), (5, 'Ditolak')]),
        ),
        migrations.AlterField(
            model_name='cooperationdocument',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
