# Generated by Django 4.1.3 on 2023-01-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_fakultas_last_ai_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperationdocument',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.cooperationdocument'),
        ),
    ]
