# Generated by Django 4.1.3 on 2023-01-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cooperationdocument_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationdocument',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cooperationdocument',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft Pengajuan'), (1, 'Belum Divalidasi'), (2, 'Disetujui Oleh Prodi'), (3, 'Disetujui Oleh Universitas'), (4, 'Draft Kadaluarsa'), (5, 'Ditolak')]),
        ),
    ]
