# Generated by Django 4.1.3 on 2023-01-25 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage
import siskerma.app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cooperationdocument_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationfile',
            name='document',
            field=models.FileField(max_length=255, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=siskerma.app.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='cooperationfile',
            name='photo',
            field=models.FileField(max_length=255, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=siskerma.app.models.path_and_rename),
        ),
        migrations.CreateModel(
            name='WorkerFcmToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.TextField()),
                ('device_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'IA'), (2, 'MOA'), (3, 'MOU')])),
                ('name', models.CharField(max_length=125)),
                ('file', models.FileField(max_length=125, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=siskerma.app.models.path_and_rename)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
