# Generated by Django 4.1.3 on 2023-03-04 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import siskerma.app.config.google_drive
import siskerma.app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_cooperationfile_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(max_length=255, storage=siskerma.app.config.google_drive.GoogleDriveStorage(),
                 upload_to=siskerma.app.models.path_and_rename)),
                ('url', models.URLField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='workerfcmtoken',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workerfcmtoken',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='workerfcmtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cooperationdocument',
            name='step',
        ),
        migrations.RemoveField(
            model_name='cooperationfile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='cooperationfile',
            name='url',
        ),
        migrations.AlterField(
            model_name='cooperationdocument',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft Pengajuan'), (1, 'Belum Divalidasi'), (2, 'Disetujui Oleh Prodi'), (
                3, 'Disetujui Oleh Fakultas'), (4, 'Disetujui Oleh Universitas'), (5, 'Draft Kadaluarsa'), (6, 'Ditolak')]),
        ),
        migrations.AlterField(
            model_name='cooperationfile',
            name='document',
            field=models.FileField(max_length=255, storage=siskerma.app.config.google_drive.GoogleDriveStorage(
            ), upload_to=siskerma.app.models.path_and_rename),
        ),
        migrations.DeleteModel(
            name='TemplateDocument',
        ),
        migrations.DeleteModel(
            name='WorkerFcmToken',
        ),
        migrations.AddField(
            model_name='cooperationdocument',
            name='evidence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='app.cooperationevidence'),
        ),
    ]
