# Generated by Django 4.1.3 on 2023-04-01 17:11

from django.db import migrations, models
import siskerma.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_cooperationdocument_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationdocument',
            name='expied_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cooperationdocument',
            name='name',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='cooperationdocument',
            name='number',
            field=models.IntegerField(default=siskerma.app.models.next_number, null=True),
        ),
        migrations.AlterField(
            model_name='cooperationdocument',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft Pengajuan'), (1, 'Belum Divalidasi'), (2, 'Disetujui Oleh Prodi'), (3, 'Disetujui Oleh Fakultas'), (4, 'Disetujui Oleh Universitas'), (5, 'Draft Kadaluarsa'), (6, 'Ditolak'), (7, 'Import')]),
        ),
    ]
