# Generated by Django 4.1.3 on 2023-05-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_cooperationdocument_expied_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperationchoice',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fakultas',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prodi',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
