# Generated by Django 4.1.3 on 2023-05-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_cooperationchoice_code_fakultas_code_prodi_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationchoice',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fakultas',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prodi',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
